
dist: "trusty"
sudo: required
language: java
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - sudo pip3 install jep
  - pip3 show jep | grep Location
  - mvn -U -q clean install

jdk:
  - oraclejdk8
  