
dist: "trusty"
sudo: required
language: java
addons:
  apt:
    packages:
      - "python3.7"
      - "python3-pip"
before_install:
  - sudo pip3 install jep
  - sudo pip3 install matplotlib
  - pip3 show jep | grep Location
  - sudo cp /usr/local/lib/python3.4/dist-packages/jep/libjep.so /lib
  - mvn -U -q clean install 
  - sudo pip3 install allennlp
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
  - source activate test-environment
  - python setup.py install
  - pip3 install allennlp

env:
  - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0, JAVA_OPTS=Djava.library.path=/usr/local/lib/python3.4/dist-packages/jep

jdk:
  - oraclejdk8

script:
  mvn -Djava.library.path=/usr/local/lib/python3.4/dist-packages/jep test 