
dist: "trusty"
sudo: required
language: java
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - sudo pip3 install jep
  - pip3 show jep | grep Location
  - ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0
  - ENV JAVA_OPTS  -Djava.library.path=/usr/local/lib/python3.4/dist-packages/jep
  - mvn -U -q clean install 


jdk:
  - oraclejdk8

script:
  mvn -Djava.library.path=/usr/local/lib/python3.4/dist-packages/jep test 